language: rust
cache: cargo

branches:
  only:
    - master

rust:
  - stable

os:
  - linux

matrix:
  include:
    - name: "rustfmt"
      before_script:
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check
    - name: "cargo clippy"
      before_script:
        - rustup component add clippy
      script:
        - cargo clippy --all
    - name: "cargo build"
      script:
        - cargo build
    - name: "cargo test"
      script:
        - cargo test
    - name: "cargo doc"
      script:
        - cargo doc --no-deps
