[package]
authors = ["Michael Lodder <redmike7@gmail.com>"]
description = """
Convenience rust crate for handling ISO 3166-1
"""
documentation = "https://docs.rs/celes/"
edition = "2018"
homepage = "https://crates.io/crates/celes"
include = [
    "src/*.rs",
    "Cargo.toml",
    "LICENSE",
    "README.md"
]
keywords = ["iso3166", "alpha2", "alpha3", "country", "codes"]
license = "Apache-2.0"
name = "celes"
readme = "README.md"
repository = "https://github.com/mikelodder7/celes"
version = "1.0.4"

[badges]
maintenance = { status = "passively-maintained" }

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"
